version: "3.3"

services:
  smarttimetable:
    container_name: smarttimetable
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
            - "./data:/code/data"
    ports:
      - "9020:5000"
    environment:
            - COMPOSE_PROJECT_NAME=smarttimetable

